(#%require "Graphics.rkt")
(#%require math)
(#%require (only racket random error))
(load "Duck ADT.rkt")
(load "Constants.rkt")
(load "Position ADT.rkt")
(load "Gun ADT.rkt")
(load "Bomb ADT.rkt")
(load "Procedures.rkt")
(load "Lives ADT.rkt")
(load "Score ADT.rkt")
(load "Hitbox ADT.rkt")
(load "Draw ADT.rkt")
(load "Droplet ADT.rkt")
(load "Round ADT.rkt")
(load "Powerup ADT.rkt")
(load "Game ADT.rkt")

;Press run to start